FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Set build-time envs if needed
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN pnpm run build --filter @stillup/web...

FROM base AS runtime
COPY --from=build /usr/src/app /usr/src/app
WORKDIR /usr/src/app/apps/web

EXPOSE 3000
CMD [ "pnpm", "start" ]
