FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build --filter @stillup/api...

FROM base AS runtime
COPY --from=build /usr/src/app /usr/src/app
WORKDIR /usr/src/app/apps/api

# Ensure prisma client is generated in runtime
RUN pnpm run db:generate

EXPOSE 4000
CMD [ "pnpm", "start" ]
